name: my_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.15.0
  - scipy>=1.11.3
  - matplotlib
  - pylops>=2.0.0
  - jupyter
  - ipython
  - tqdm
  - cupy
  - joblib
  - pip:
    - devito
    - scikit-fmm
    - spgl1
    - pytest-runner
    - setuptools_scm
    - segyio